### ISSUE TITLE
No documenation is repo

### ISSUE THREAD

**Issue by arimer** [mbeddr/mps-qa#1]
@danielratiu Due to the fact that this is a public repo a minimum amount of documenation would be required. 
**Some ideas**

* what is the project structure?
* what is the purpose of this repo?
* how to use?
* how to contribute?
* how to build?
* which MPS version is supported?

I think we need a miminum amount of documenation here otherwise otherwise users are clueless what to do with it?

**Comment by danielratiu** [comment]
I have updated the readme.md with the relevant information

@arimer any further feedback is highly welcomed

**Comment by arimer** [comment]
Thanks! I'll have a look.
